server {
    listen 80;
    listen [::]:80;
    server_name example.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name example.com;

    root /var/www/example.com/public;
    index index.html;

    ssl_certificate /opt/acme-cert-manager/certs/example.com/fullchain.pem;
    ssl_certificate_key /opt/acme-cert-manager/certs/example.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;

    location / {
        try_files $uri $uri/ =404;
    }
}
